import Link from "next/link";
import SiteNav from "@/components/home/SiteNav";
import SiteFooter from "@/components/home/SiteFooter";

export const metadata = { title: "Privacy Policy | Mach Twenty 11" };

const SECTIONS = [
  {
    title: "1. Information We Collect",
    body: `We collect information you provide directly — name, email, company, DOT/MC numbers, insurance
    documentation, and payment details — along with information generated by using the platform, such as
    shipment details, bid history, messages, and device/usage data.`,
  },
  {
    title: "2. How We Use Information",
    body: `We use collected information to operate the marketplace: matching shipments with carriers, processing
    payments and payouts, verifying carrier credentials, sending shipment and billing notifications, and
    improving rate-matching and fraud-detection systems.`,
  },
  {
    title: "3. Sharing With Carriers and Shippers",
    body: `When you post or bid on a shipment, relevant details (route, cargo description, company name, and —
    once awarded — contact information) are shared with the counterparty needed to fulfill that shipment.
    We do not sell personal information to third parties.`,
  },
  {
    title: "4. Payment Processing",
    body: `Payments and carrier payouts are processed by Stripe. We do not store full payment card numbers or
    bank account details on our servers — those are held by Stripe under its own privacy and security terms.`,
  },
  {
    title: "5. Data Retention",
    body: `We retain shipment, billing, and dispute records for as long as needed to meet accounting, tax, and
    legal obligations, and to resolve disputes after a shipment is delivered.`,
  },
  {
    title: "6. Your Rights",
    body: `Depending on your location, you may have rights to access, correct, export, or delete your personal
    information, and to withdraw newsletter consent at any time via the unsubscribe link in any email.`,
  },
  {
    title: "7. Contact",
    body: `Questions about this policy can be sent to support@mach2011.com.`,
  },
];

export default function PrivacyPolicyPage() {
  return (
    <>
      <SiteNav />
      <main className="hp-body bg-white pb-24 pt-32 text-hpink">
        <div className="mx-auto max-w-3xl px-6 md:px-10">
          <p className="hp-mono text-xs tracking-[0.18em] text-hpcyandeep">LEGAL</p>
          <h1 className="hp-display mt-3 text-3xl font-semibold md:text-4xl">Privacy Policy</h1>
          <p className="hp-body mt-2 text-sm text-black/50">Last updated: draft, not yet published</p>

          <div className="mt-4 rounded-lg border border-m20amber/40 bg-m20amber/10 p-4 text-sm text-hpink">
            <strong>Draft — pending legal review.</strong> This page is a structural placeholder written to
            cover the topics a freight marketplace privacy policy needs. It has not been reviewed by counsel
            and should not be treated as your finalized policy until it is.
          </div>

          <div className="mt-10 space-y-8">
            {SECTIONS.map((s) => (
              <section key={s.title}>
                <h2 className="hp-display text-lg font-semibold">{s.title}</h2>
                <p className="hp-body mt-2 text-sm leading-relaxed text-black/65">{s.body}</p>
              </section>
            ))}
          </div>

          <p className="hp-body mt-12 text-sm text-black/50">
            See also our <Link href="/terms" className="text-hpcyandeep underline">Terms of Service</Link>.
          </p>
        </div>
      </main>
      <SiteFooter />
    </>
  );
}
